/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Steps */
        get: operations["list_steps_strategies_steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_strategies_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__pid__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_projects__pid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Source */
        post: operations["upload_source_projects__pid__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_projects__pid__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Translation */
        post: operations["start_translation_projects__pid__translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Only */
        post: operations["prepare_only_projects__pid__prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assemble Output */
        post: operations["assemble_output_projects__pid__assemble_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_projects__pid__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_projects__pid__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_projects__pid__config_get"];
        /** Save Config */
        put: operations["save_config_projects__pid__config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/config/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Defaults */
        get: operations["project_defaults_projects__pid__config_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Config */
        post: operations["validate_config_projects__pid__config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_projects__pid__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/models/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Models */
        post: operations["check_models_projects__pid__models_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Stats */
        get: operations["project_stats_projects__pid__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workflow
         * @description Describe the latest workflow using its frozen configuration, not edited settings.
         */
        get: operations["workflow_projects__pid__workflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        /** Save */
        put: operations["save_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Settings */
        get: operations["default_settings_settings_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_settings_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_projects__pid__report_get"];
        put?: never;
        /** Regenerate Report */
        post: operations["regenerate_report_projects__pid__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/subtitles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subtitles */
        get: operations["get_subtitles_projects__pid__subtitles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/subtitles/{cueid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Subtitle */
        put: operations["edit_subtitle_projects__pid__subtitles__cueid__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chapters */
        get: operations["list_chapters_projects__pid__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/chapters/{ci}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chapter */
        get: operations["get_chapter_projects__pid__chapters__ci__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/chapters/{ci}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Chapter Title */
        put: operations["update_chapter_title_projects__pid__chapters__ci__title_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/chapters/{ci}/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Translate Chapter */
        post: operations["translate_chapter_projects__pid__chapters__ci__translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/glossary/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Terms */
        get: operations["list_terms_projects__pid__glossary_terms_get"];
        put?: never;
        /** Add Term */
        post: operations["add_term_projects__pid__glossary_terms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/glossary/terms/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Term */
        put: operations["update_term_projects__pid__glossary_terms__source__put"];
        post?: never;
        /** Delete Term */
        delete: operations["delete_term_projects__pid__glossary_terms__source__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/glossary/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conflicts */
        get: operations["list_conflicts_projects__pid__glossary_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/glossary/conflicts/{cid}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Conflict */
        post: operations["resolve_conflict_projects__pid__glossary_conflicts__cid__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/glossary/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Glossary */
        get: operations["export_glossary_projects__pid__glossary_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/glossary/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Glossary */
        post: operations["import_glossary_projects__pid__glossary_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/review/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Ai Review */
        post: operations["run_ai_review_projects__pid__review_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/review/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_projects__pid__review_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/review/runs/{rid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_projects__pid__review_runs__rid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/review/{ci}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chapter For Review */
        get: operations["get_chapter_for_review_projects__pid__review__ci__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/review/{ci}/segments/{seg_idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Segment */
        put: operations["edit_segment_projects__pid__review__ci__segments__seg_idx__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/review/{ci}/segments/{seg_idx}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Segment History */
        get: operations["segment_history_projects__pid__review__ci__segments__seg_idx__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/review/{ci}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Reviewed */
        post: operations["mark_reviewed_projects__pid__review__ci__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_projects__pid__analysis_get"];
        /** Update Analysis */
        put: operations["update_analysis_projects__pid__analysis_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/chapter-digests/{ci}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Chapter Digest */
        put: operations["update_chapter_digest_projects__pid__chapter_digests__ci__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_projects__pid__exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_projects__pid__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_projects__pid__exports__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_projects__pid__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisOut */
        AnalysisOut: {
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
            /** Chapter Digests */
            chapter_digests: components["schemas"]["ChapterDigest"][];
        };
        /** AnalysisUpdate */
        AnalysisUpdate: {
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
        };
        /** AssembleEnqueued */
        AssembleEnqueued: {
            /** Job Id */
            job_id: string;
            /** Project Id */
            project_id: string;
            /** Kind */
            kind: string;
            /** Export Id */
            export_id: number;
        };
        /** Body_create_project_projects_post */
        Body_create_project_projects_post: {
            /** Project */
            project: string;
            /** File */
            file: string;
        };
        /** Body_upload_source_projects__pid__upload_post */
        Body_upload_source_projects__pid__upload_post: {
            /** File */
            file: string;
            /** Fmt */
            fmt?: string | null;
        };
        /** Capabilities */
        Capabilities: {
            /** Languages */
            languages: components["schemas"]["LanguageOption"][];
            /** Input Formats */
            input_formats: string[];
            /** Output Formats */
            output_formats: string[];
            pdf: components["schemas"]["PDFCapabilities"];
            /** Providers */
            providers: string[];
            /** Operations */
            operations: {
                [key: string]: unknown;
            }[];
        };
        /** ChapterDigest */
        ChapterDigest: {
            /** Index */
            index: number;
            /** Title */
            title: string;
            /** Digest */
            digest: string;
        };
        /** ChapterSegments */
        ChapterSegments: {
            /** Index */
            index: number;
            /**
             * Title
             * @default
             */
            title: string;
            /** Title Translated */
            title_translated?: string | null;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /**
             * Review Issues
             * @default []
             */
            review_issues: {
                [key: string]: unknown;
            }[];
        };
        /** ChapterSummary */
        ChapterSummary: {
            /** Index */
            index: number;
            /**
             * Title
             * @default
             */
            title: string;
            /** Title Translated */
            title_translated?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Word Count
             * @default 0
             */
            word_count: number;
            /**
             * Target Word Count
             * @default 0
             */
            target_word_count: number;
            /**
             * Review Issue Count
             * @default 0
             */
            review_issue_count: number;
            /**
             * Review Status
             * @default pending
             */
            review_status: string;
        };
        /** ChapterTitleOut */
        ChapterTitleOut: {
            /** Index */
            index: number;
            /** Title Translated */
            title_translated: string;
        };
        /** ChapterTitleUpdate */
        ChapterTitleUpdate: {
            /** Title Translated */
            title_translated: string;
            /** Expected Title Translated */
            expected_title_translated: string | null;
        };
        /** ConfigInput */
        ConfigInput: {
            /** Yaml */
            yaml: string;
        };
        /** ConflictOut */
        ConflictOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Existing Target */
            existing_target: string | null;
            /** Proposed Target */
            proposed_target: string | null;
            /** Chapter */
            chapter: number | null;
            /** Note */
            note?: string | null;
        };
        /** DigestUpdate */
        DigestUpdate: {
            /** Digest */
            digest: string;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /**
             * Payload
             * @default {}
             */
            payload: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at?: string | null;
        };
        /** ExportOut */
        ExportOut: {
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Project Id */
            project_id: string;
            /** Format */
            format: string;
            /** Status */
            status: string;
            /** Path */
            path?: string | null;
            /** Size */
            size?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Format */
            format?: ("epub" | "txt" | "html" | "markdown" | "pdf" | "docx" | "srt") | null;
            /**
             * Bilingual
             * @default false
             */
            bilingual: boolean;
            /**
             * Order
             * @default target_first
             * @enum {string}
             */
            order: "target_first" | "source_first";
            /**
             * About Page
             * @default true
             */
            about_page: boolean;
            /** Include Translator Afterword */
            include_translator_afterword?: boolean | null;
            /**
             * Preserve Source Style
             * @default false
             */
            preserve_source_style: boolean;
            /** Punctuation Normalize */
            punctuation_normalize?: boolean | null;
            /**
             * Pdf Engine
             * @default weasyprint
             * @enum {string}
             */
            pdf_engine: "weasyprint" | "fpdf2";
        };
        /** GlobalConfigInput */
        GlobalConfigInput: {
            /** Yaml */
            yaml: string;
            /** Default Template */
            default_template: string;
            /** Revision */
            revision: number;
            /** Model Renames */
            model_renames?: {
                [key: string]: string;
            };
        };
        /** GlobalConfigOut */
        GlobalConfigOut: {
            /** Yaml */
            yaml: string;
            /** Effective */
            effective: {
                [key: string]: unknown;
            };
            /** Default Template */
            default_template: string;
            /** Revision */
            revision: number;
        };
        /** GlossaryImport */
        GlossaryImport: {
            /** Terms */
            terms: components["schemas"]["TermIn"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobEnqueued */
        JobEnqueued: {
            /** Job Id */
            job_id: string;
            /** Project Id */
            project_id: string;
            /** Kind */
            kind: string;
        };
        /** LanguageOption */
        LanguageOption: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** Message */
        Message: {
            /** Message */
            message: string;
            /** Detail */
            detail?: unknown;
        };
        /** ModelCheckRequest */
        ModelCheckRequest: {
            /**
             * Workflow
             * @default translate
             * @enum {string}
             */
            workflow: "prepare" | "translate" | "review" | "srt";
        };
        /** ModelCheckResult */
        ModelCheckResult: {
            /** Valid */
            valid: boolean;
            /** Operations */
            operations: string[];
        };
        /** PDFCapabilities */
        PDFCapabilities: {
            /** Backends */
            backends: string[];
            /** Engines */
            engines: string[];
            /** Export Backends */
            export_backends: string[];
        };
        /** PreviewChapter */
        PreviewChapter: {
            /** Index */
            index: number;
            /** Title */
            title: string;
            /** Word Count */
            word_count: number;
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Fmt */
            fmt?: string | null;
            /** Source Lang */
            source_lang?: string | null;
            /** Target Lang */
            target_lang?: string | null;
            /**
             * Status
             * @default created
             */
            status: string;
            /** Error */
            error?: string | null;
            /**
             * Initialized
             * @default false
             */
            initialized: boolean;
            /** Strategy */
            strategy?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ProjectConfigOut */
        ProjectConfigOut: {
            /** Yaml */
            yaml: string;
            /** Effective */
            effective: {
                [key: string]: unknown;
            };
            /** Routes */
            routes: {
                [key: string]: unknown;
            }[];
            /** Editable */
            editable: boolean;
            /** Registered Models */
            registered_models: {
                [key: string]: unknown;
            };
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Source Lang
             * @default auto
             */
            source_lang: string;
            /**
             * Target Lang
             * @default zh
             */
            target_lang: string;
            /** Strategy */
            strategy?: {
                [key: string]: unknown;
            };
            /**
             * Prepare
             * @default false
             */
            prepare: boolean;
            /** Pdf Backend */
            pdf_backend?: ("mineru" | "babeldoc") | null;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Fmt */
            fmt?: string | null;
            /** Source Lang */
            source_lang?: string | null;
            /** Target Lang */
            target_lang?: string | null;
            /**
             * Status
             * @default created
             */
            status: string;
            /** Error */
            error?: string | null;
            /**
             * Initialized
             * @default false
             */
            initialized: boolean;
            /** Strategy */
            strategy?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at?: string | null;
            /** Book Title */
            book_title?: string | null;
            /**
             * Chapter Count
             * @default 0
             */
            chapter_count: number;
            /**
             * Total Word Count
             * @default 0
             */
            total_word_count: number;
            /**
             * Done Chapters
             * @default 0
             */
            done_chapters: number;
            /** Source Meta */
            source_meta?: {
                [key: string]: unknown;
            };
        };
        /** ProjectStats */
        ProjectStats: {
            /** Usage */
            usage?: {
                [key: string]: unknown;
            };
            /** Timing */
            timing?: {
                [key: string]: unknown;
            };
        };
        /** ResolveConflict */
        ResolveConflict: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "current" | "proposed" | "custom";
            /** Target */
            target?: string | null;
        };
        /** ReviewItem */
        ReviewItem: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "issue" | "change" | "publication";
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Suggestion
             * @default
             */
            suggestion: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "fixed" | "failed" | "unchanged";
            location?: components["schemas"]["ReviewLocation"] | null;
            /** Evidence */
            evidence?: components["schemas"]["ReviewLocation"][];
            /** Issue */
            issue?: {
                [key: string]: unknown;
            };
            /** Changes */
            changes?: {
                [key: string]: unknown;
            }[];
            /** Publications */
            publications?: {
                [key: string]: unknown;
            }[];
        };
        /** ReviewLocation */
        ReviewLocation: {
            /** Chapter */
            chapter: number;
            /** Text Index */
            text_index: number;
            /** Segment Index */
            segment_index: number;
            /** Chapter Title */
            chapter_title: string;
            /** Source */
            source: string;
            /** Current Target */
            current_target: string | null;
        };
        /** ReviewRun */
        ReviewRun: {
            /** Id */
            id: string;
            /** Review Id */
            review_id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Issues */
            issues?: {
                [key: string]: unknown;
            }[];
            /** Changes */
            changes?: {
                [key: string]: unknown;
            }[];
            /** Autofix */
            autofix?: {
                [key: string]: unknown;
            };
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
            /** Result */
            result?: {
                [key: string]: unknown;
            };
            /** Items */
            items?: components["schemas"]["ReviewItem"][];
        };
        /** ReviewRunRequest */
        ReviewRunRequest: {
            /** Autofix */
            autofix?: boolean | null;
        };
        /** SegmentEdit */
        SegmentEdit: {
            /** Target */
            target: string;
            /** Expected Target */
            expected_target: string | null;
        };
        /** SegmentOut */
        SegmentOut: {
            /** Index */
            index: number;
            /** Source */
            source: string;
            /** Target */
            target?: string | null;
            /** Target Before Polish */
            target_before_polish?: string | null;
            /** Anchor */
            anchor?: string | null;
            /**
             * Kind
             * @default text
             */
            kind: string;
        };
        /** SegmentRevision */
        SegmentRevision: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "translation" | "polish" | "manual" | "update" | "snapshot" | "before_polish";
            /** Before */
            before: string | null;
            /** After */
            after: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** StartTranslation */
        StartTranslation: {
            /** Strategy */
            strategy?: {
                [key: string]: unknown;
            } | null;
        };
        /** StepDef */
        StepDef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /**
             * Always On
             * @default false
             */
            always_on: boolean;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Group */
            group?: string | null;
            /**
             * Depends On
             * @default []
             */
            depends_on: string[];
            /** Description */
            description?: string | null;
            /** Output */
            output?: string | null;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
        };
        /** StrategyTemplateOut */
        StrategyTemplateOut: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Time Factor
             * @default 1
             */
            time_factor: number;
            /**
             * Recommended
             * @default false
             */
            recommended: boolean;
            /** Steps */
            steps: {
                [key: string]: unknown;
            };
        };
        /** SubtitleCue */
        SubtitleCue: {
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Timestamp */
            timestamp: string;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Source */
            source: string;
            /** Target */
            target?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /** SubtitleResult */
        SubtitleResult: {
            /** Cues */
            cues: components["schemas"]["SubtitleCue"][];
            /** Completed */
            completed: number;
            /** Total */
            total: number;
        };
        /** TargetEdit */
        TargetEdit: {
            /** Target */
            target: string;
        };
        /** TermIn */
        TermIn: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Reading
             * @default
             */
            reading: string;
            /**
             * Type
             * @default term
             */
            type: string;
            /**
             * Gender
             * @default
             */
            gender: string;
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** TermOut */
        TermOut: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Reading
             * @default
             */
            reading: string;
            /**
             * Type
             * @default term
             */
            type: string;
            /**
             * Gender
             * @default
             */
            gender: string;
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /** First Chapter */
            first_chapter?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** UploadPreview */
        UploadPreview: {
            /** Title */
            title: string;
            /** Fmt */
            fmt: string;
            /** Chapter Count */
            chapter_count: number;
            /** Total Word Count */
            total_word_count: number;
            /** Source Lang */
            source_lang?: string | null;
            /** Chapters */
            chapters?: components["schemas"]["PreviewChapter"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowOut */
        WorkflowOut: {
            /** Source */
            source: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Run Id */
            run_id?: string | null;
            /** Review Id */
            review_id?: string | null;
            /** Stages */
            stages: components["schemas"]["WorkflowStage"][];
            /** Progress */
            progress?: {
                [key: string]: unknown;
            } | null;
        };
        /** WorkflowStage */
        WorkflowStage: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_steps_strategies_steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepDef"][];
                };
            };
        };
    };
    list_templates_strategies_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyTemplateOut"][];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_project_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__pid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_projects__pid__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_projects__pid__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_projects__pid__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_translation_projects__pid__translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartTranslation"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_only_projects__pid__prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assemble_output_projects__pid__assemble_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssembleEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_projects__pid__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_projects__pid__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    get_config_projects__pid__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_config_projects__pid__config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_defaults_projects__pid__config_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_config_projects__pid__config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_projects__pid__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_models_projects__pid__models_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCheckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_stats_projects__pid__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_projects__pid__workflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalConfigOut"];
                };
            };
        };
    };
    save_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlobalConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    default_settings_settings_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalConfigOut"];
                };
            };
        };
    };
    validate_settings_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlobalConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_projects__pid__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_report_projects__pid__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtitles_projects__pid__subtitles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtitleResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_subtitle_projects__pid__subtitles__cueid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                cueid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters_projects__pid__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_projects__pid__chapters__ci__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSegments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chapter_title_projects__pid__chapters__ci__title_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterTitleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterTitleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_chapter_projects__pid__chapters__ci__translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_terms_projects__pid__glossary_terms_get: {
        parameters: {
            query?: {
                q?: string | null;
                type?: string | null;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_term_projects__pid__glossary_terms_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_term_projects__pid__glossary_terms__source__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                source: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_term_projects__pid__glossary_terms__source__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conflicts_projects__pid__glossary_conflicts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_conflict_projects__pid__glossary_conflicts__cid__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                cid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveConflict"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_glossary_projects__pid__glossary_export_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_glossary_projects__pid__glossary_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ai_review_projects__pid__review_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_projects__pid__review_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_projects__pid__review_runs__rid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_for_review_projects__pid__review__ci__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSegments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_segment_projects__pid__review__ci__segments__seg_idx__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
                seg_idx: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_history_projects__pid__review__ci__segments__seg_idx__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
                seg_idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRevision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_reviewed_projects__pid__review__ci__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_projects__pid__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_analysis_projects__pid__analysis_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chapter_digest_projects__pid__chapter_digests__ci__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                ci: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DigestUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_projects__pid__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_projects__pid__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssembleEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_projects__pid__exports__export_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                export_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_projects__pid__events_get: {
        parameters: {
            query?: {
                type?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
